# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FpJHjbwd_CUTbh5z-lgIqVT50Evx9faE
"""

import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from datetime import datetime
import streamlit as st

# ----------------------------
# 🎨 STREAMLIT CONFIG
# ----------------------------
st.set_page_config(
    page_title="AI Pricing Agent Dashboard",
    layout="wide"
)

st.title("🧠 AI Agent for Dynamic Pricing Optimization")
st.caption("Enchanto | Dynamic Pricing for E-commerce Products")

EXCEL_FILE = "Enchanto_Products.xlsx"


# ----------------------------
# 📥 DATA LOADING & SIMULATION
# ----------------------------
@st.cache_data
def load_and_simulate_data(filepath: str) -> pd.DataFrame:
    try:
        try:
            df = pd.read_excel(filepath, sheet_name="Products")
        except ValueError:
            df = pd.read_excel(filepath, sheet_name=0)

        cols = ['Product ID', 'Product Name', 'Category', 'Price', 'Stock availability']
        for c in cols:
            if c not in df.columns:
                df[c] = 0 if c == "Price" else "Unknown"

        df = df[cols].copy()
        df["Price"] = df["Price"].astype(str).str.replace(r"[^\d.]", "", regex=True)
        df["Price"] = pd.to_numeric(df["Price"], errors="coerce").fillna(0)

        np.random.seed(42)
        df["Cost_Price"] = df["Price"] * 0.40
        df["Competitor_Price"] = (df["Price"] * np.random.uniform(0.8, 1.2, len(df))).round(2)
        df["Demand_Score"] = np.random.randint(1, 11, len(df))
        df["Inventory_Count"] = np.random.randint(0, 150, len(df))

        return df

    except FileNotFoundError:
        st.error(f"File '{filepath}' not found.")
        return pd.DataFrame()


def ai_pricing_agent(row):
    base = row["Price"]
    competitor = row["Competitor_Price"]
    demand = row["Demand_Score"]
    inventory = row["Inventory_Count"]
    cost = row["Cost_Price"]

    suggested = base
    reasoning = []

    if inventory < 20 and demand > 7:
        suggested *= 1.20
        reasoning.append("🔥 Scarcity Surge (+20%)")

    elif inventory > 100 and demand < 4:
        suggested *= 0.90
        reasoning.append("🏷️ Clearance Move (-10%)")

    if suggested > competitor * 1.15:
        suggested = competitor * 1.10
        reasoning.append("⚔️ Competitor Match")

    min_price = cost * 1.20
    if suggested < min_price:
        suggested = min_price
        reasoning.append("🛡️ Margin Protection")

    return round(suggested, 2), ", ".join(reasoning)


@st.cache_data
def prepare_data():
    df = load_and_simulate_data(EXCEL_FILE)
    if df.empty:
        return df

    ai_results = df.apply(lambda r: ai_pricing_agent(r), axis=1)
    df["AI_Recommended_Price"] = ai_results.apply(lambda x: x[0])
    df["Pricing_Logic"] = ai_results.apply(lambda x: x[1])

    return df


@st.cache_data
def generate_history(row):
    dates = pd.date_range(end=datetime.today(), periods=30)
    prices = [row["Competitor_Price"]]

    for _ in range(29):
        change = np.random.uniform(-5, 5)
        prices.append(max(prices[-1] + change, row["Cost_Price"]))

    return pd.DataFrame({"Date": dates, "Competitor_Price": prices[::-1]})


# ----------------------------
# 🧮 MAIN DASHBOARD
# ----------------------------
product_data = prepare_data()
if product_data.empty:
    st.stop()

st.sidebar.header("🔍 Filters")
category = st.sidebar.selectbox("📂 Category", sorted(product_data["Category"].unique()))
filtered = product_data[product_data["Category"] == category]

product_name = st.sidebar.selectbox("🧴 Product", filtered["Product Name"].unique())

row = filtered[filtered["Product Name"] == product_name].iloc[0]
history = generate_history(row)

# ----------------------------
# 💎 HEADER CARD (FIXED)
# ----------------------------
header_html = f"""
<div style="background: linear-gradient(90deg, #2c3e50 0%, #4ca1af 100%);
            color: white; padding: 20px; border-radius: 12px; margin-bottom: 20px;">

    <h1 style="margin:0; font-size:28px;">💎 {row['Product Name']}</h1>
    <h3 style="margin:5px 0 15px 0; opacity:0.9; font-size:16px;">
        {row['Category']} | SKU: {row['Product ID']}
    </h3>

    <div style="display: flex; justify-content: space-between; text-align: center; gap: 20px;">

        <div style="background: rgba(255,255,255,0.15); padding: 12px; border-radius: 8px; flex: 1;">
            <div style="font-size: 12px; text-transform: uppercase;">Current Price</div>
            <div style="font-size: 26px; font-weight: bold;">₹{row['Price']:.2f}</div>
        </div>

        <div style="background: rgba(255,255,255,0.15); padding: 12px; border-radius: 8px; flex: 1;">
            <div style="font-size: 12px; text-transform: uppercase;">Competitor</div>
            <div style="font-size: 26px; font-weight: bold; color:#ffcccc;">₹{row['Competitor_Price']:.2f}</div>
        </div>

        <div style="background: white; color:#2c3e50; padding: 12px; border-radius: 8px; flex: 1;">
            <div style="font-size: 12px; text-transform: uppercase;">AI Recommended</div>
            <div style="font-size: 26px; font-weight: bold;">₹{row['AI_Recommended_Price']:.2f}</div>
        </div>

    </div>

    <div style="margin-top: 12px; text-align: center; font-size: 14px;">
        🤖 <b>AI Logic:</b> {row['Pricing_Logic'] if row['Pricing_Logic'] else "Stable Market Conditions"}
    </div>

</div>
"""

st.markdown(header_html, unsafe_allow_html=True)


# ----------------------------
# 📊 PLOTLY CHARTS
# ----------------------------
col1, col2 = st.columns(2)

# 1️⃣ PRICE COMPARISON (Bar Chart)
with col1:
    fig1 = px.bar(
        x=["Current", "Competitor", "AI Price"],
        y=[row["Price"], row["Competitor_Price"], row["AI_Recommended_Price"]],
        color=["Current", "Competitor", "AI Price"],
        color_discrete_sequence=["gray", "red", "green"],
        title="Price Benchmark Comparison",
        text=[row["Price"], row["Competitor_Price"], row["AI_Recommended_Price"]]
    )
    fig1.update_traces(texttemplate="₹%{text}", textposition="outside")
    fig1.update_layout(yaxis_title="Price (₹)")
    st.plotly_chart(fig1, use_container_width=True)

# 2️⃣ PROFITABILITY ANALYSIS (Stacked)
with col2:
    profit_curr = row["Price"] - row["Cost_Price"]
    profit_ai = row["AI_Recommended_Price"] - row["Cost_Price"]

    fig2 = go.Figure()
    fig2.add_trace(go.Bar(
        name="Cost",
        x=["Current", "AI"],
        y=[row["Cost_Price"], row["Cost_Price"]],
        marker_color="#95a5a6"
    ))
    fig2.add_trace(go.Bar(
        name="Profit",
        x=["Current", "AI"],
        y=[profit_curr, profit_ai],
        marker_color="#f1c40f"
    ))

    fig2.update_layout(
        barmode="stack",
        title="Profitability Analysis",
        yaxis_title="₹ per Unit"
    )
    st.plotly_chart(fig2, use_container_width=True)

# 3️⃣ COMPETITOR PRICE TREND (Line Chart)
fig3 = px.line(
    history,
    x="Date",
    y="Competitor_Price",
    title="Competitor Price Trend (30 Days)",
    markers=True,
    color_discrete_sequence=["red"]
)
fig3.update_layout(xaxis_title="Date", yaxis_title="Price (₹)")
st.plotly_chart(fig3, use_container_width=True)

# 4️⃣ INVENTORY BURN PROJECTION
days = np.arange(0, 30)
burn_rate = row["Demand_Score"]
stock = [max(0, row["Inventory_Count"] - d * burn_rate) for d in days]

fig4 = go.Figure()
fig4.add_trace(go.Scatter(
    x=days, y=stock,
    mode="lines+markers",
    fill="tozeroy",
    line=dict(color="#2980b9"),
    name="Stock Level"
))
fig4.add_hline(y=0, line_dash="dot", line_color="red")
fig4.update_layout(
    title=f"Inventory Burn Projection (Demand Score: {row['Demand_Score']}/10)",
    xaxis_title="Days Ahead",
    yaxis_title="Stock Units"
)
st.plotly_chart(fig4, use_container_width=True)

# Optional: raw data
with st.expander("🔎 Show Raw Data"):
    st.dataframe(product_data)